service: aws-python3 # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  region: 'us-east-1'
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:*'
      Resource:
        - SNSTOPICO
    - Effect: 'Allow'
      Action:
        - 'sqs:*'
      Resource:
        - SQSTOPICO
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::lab-fiap-78aoj-339812"

functions:
  book:
    handler: handler.book
    events:
      - http:
        path: book/create
        method: get
  sell:
    handler: handler.sell
    events:
      - http:
        path: sell/book
        method: get
  consumer:
    handler: handler.consumer
    events:
      - sqs: SQSTOPICO
